version: '3.8'
services:
  backend:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    platform: linux/amd64
    restart: unless-stopped
    pull_policy: ${PULL_POLICY}
    depends_on:
      configurator:
        condition: service_completed_successfully
    env_file:
      - ./helpdesk_prod_setup.env
    volumes:
      - backend-vol:/home/frappe/frappe-bench/sites

  configurator:
    image: ${CUSTOM_IMAGE}:${CUSTOM_TAG}
    command: configure
    env_file:
      - ./helpdesk_prod_setup.env
    restart: on-failure

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-vol:/var/lib/mysql

  redis-cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis-socketio-vol:/data

volumes:
  backend-vol:
  db-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
