version: "3.7"
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: r00T@!travelthru
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    working_dir: /home/frappe
    environment:
      - SHELL=/bin/bash
    command: >
      bash -c "
      if [ -d '/home/frappe/frappe-bench/apps/frappe' ]; then
          echo 'Bench already exists, skipping init';
          cd frappe-bench;
      else
          echo 'Creating new bench...';
          bench init --skip-redis-config-generation frappe-bench --version version-15;
          cd frappe-bench;

          bench set-mariadb-host mariadb;
          bench set-redis-cache-host redis://redis:6379;
          bench set-redis-queue-host redis://redis:6379;
          bench set-redis-socketio-host redis://redis:6379;

          sed -i '/redis/d' ./Procfile;
          sed -i '/watch/d' ./Procfile;

          bench get-app helpdesk --branch main;

          bench new-site desk.travelthru.com \
            --force \
            --mariadb-root-password r00T@!travelthru \
            --admin-password r00T@!travelthru \
            --no-mariadb-socket;

          bench --site desk.travelthru.com install-app helpdesk;
          bench --site desk.travelthru.com set-config developer_mode 1;
          bench --site desk.travelthru.com set-config mute_emails 1;
          bench --site desk.travelthru.com set-config server_script_enabled 1;
      fi;

      cd /home/frappe/frappe-bench;
      bench --site desk.travelthru.com clear-cache;
      bench build --app helpdesk --force;
      bench use desk.travelthru.com;

      exec bench start;
      "
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
